/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.skravetz.centromedico.vista;

import com.skravetz.centromedico.controlador.Registro;
import com.skravetz.centromedico.modelo.Paciente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastiankravetz
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCarrera
     */
    public Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel_nombreCarrera = new javax.swing.JLabel();
        jText_rutPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jText_nombrePaciente = new javax.swing.JTextField();
        jRadio_pacienteFemenino = new javax.swing.JRadioButton();
        jRadio_pacienteMasculino = new javax.swing.JRadioButton();
        jText_edadPaciente = new javax.swing.JTextField();
        jText_direccionPaciente = new javax.swing.JTextField();
        jText_ciudadPaciente = new javax.swing.JTextField();
        jRadio_pacienteConIsapre = new javax.swing.JRadioButton();
        jRadio_pacienteSinIsapre = new javax.swing.JRadioButton();
        jCheckBox_esDonante = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jBtn_agregarPaciente = new javax.swing.JButton();
        jBtn_limpiarDatosPaciente = new javax.swing.JButton();
        jBtn_salirAgregarPaciente = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Paciente");

        jPanel2.setBackground(new java.awt.Color(174, 220, 223));

        jLabel_nombreCarrera.setText("Rut:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Género:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("Ciudad:");

        jLabel7.setText("Isapre:");

        jLabel8.setText("Donante:");

        jRadio_pacienteFemenino.setText("Femenino");
        jRadio_pacienteFemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadio_pacienteFemeninoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadio_pacienteFemeninoMouseReleased(evt);
            }
        });
        jRadio_pacienteFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacienteFemeninoActionPerformed(evt);
            }
        });

        jRadio_pacienteMasculino.setText("Masculino");
        jRadio_pacienteMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadio_pacienteMasculinoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadio_pacienteMasculinoMouseReleased(evt);
            }
        });

        jRadio_pacienteConIsapre.setText("Sí");
        jRadio_pacienteConIsapre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadio_pacienteConIsapreMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadio_pacienteConIsapreMouseReleased(evt);
            }
        });
        jRadio_pacienteConIsapre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacienteConIsapreActionPerformed(evt);
            }
        });

        jRadio_pacienteSinIsapre.setText("No");
        jRadio_pacienteSinIsapre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadio_pacienteSinIsapreMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadio_pacienteSinIsapreMouseReleased(evt);
            }
        });
        jRadio_pacienteSinIsapre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_pacienteSinIsapreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_direccionPaciente)
                                    .addComponent(jText_ciudadPaciente)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel_nombreCarrera))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText_rutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_nombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 24, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_esDonante))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jRadio_pacienteFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio_pacienteMasculino))
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(jText_edadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(jRadio_pacienteConIsapre)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadio_pacienteSinIsapre))
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombreCarrera)
                    .addComponent(jText_rutPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_nombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadio_pacienteFemenino)
                    .addComponent(jRadio_pacienteMasculino))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jText_edadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jText_direccionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jText_ciudadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadio_pacienteConIsapre)
                    .addComponent(jRadio_pacienteSinIsapre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_esDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(29, 157, 175));

        jBtn_agregarPaciente.setText("Guardar");
        jBtn_agregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_agregarPacienteActionPerformed(evt);
            }
        });

        jBtn_limpiarDatosPaciente.setText("Limpiar");
        jBtn_limpiarDatosPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_limpiarDatosPacienteActionPerformed(evt);
            }
        });

        jBtn_salirAgregarPaciente.setText("Salir");
        jBtn_salirAgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_salirAgregarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_agregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jBtn_limpiarDatosPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_salirAgregarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBtn_agregarPaciente)
                .addGap(18, 18, 18)
                .addComponent(jBtn_limpiarDatosPaciente)
                .addGap(18, 18, 18)
                .addComponent(jBtn_salirAgregarPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_agregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_agregarPacienteActionPerformed
        // TODO add your handling code here:
        
        
        String rutPaciente = this.jText_rutPaciente.getText();
        String nombrePaciente = this.jText_nombrePaciente.getText();
        String generoPaciente = "";
        int edadPaciente = Integer.parseInt(this.jText_edadPaciente.getText());
        String direccionPaciente = this.jText_direccionPaciente.getText();
        String ciudadPaciente = this.jText_ciudadPaciente.getText();
        String isaprePaciente = "";
        boolean esDonante = this.jCheckBox_esDonante.isSelected();
        
        if (this.jRadio_pacienteFemenino.isSelected() && !this.jRadio_pacienteMasculino.isSelected()) {
            generoPaciente = "F";
        } else if (!this.jRadio_pacienteFemenino.isSelected() && this.jRadio_pacienteMasculino.isSelected()) {
            generoPaciente = "M";
        }
        
        if(this.jRadio_pacienteConIsapre.isSelected() && !this.jRadio_pacienteSinIsapre.isSelected()){
            isaprePaciente = "S";
        } else if (!this.jRadio_pacienteConIsapre.isSelected() && this.jRadio_pacienteSinIsapre.isSelected()) {
            isaprePaciente = "N";
        }
        
        Paciente nuevoPaciente = new Paciente();
        nuevoPaciente.setRut(rutPaciente);
        nuevoPaciente.setNombre(nombrePaciente);
        nuevoPaciente.setGenero(generoPaciente);
        nuevoPaciente.setEdad(edadPaciente);
        nuevoPaciente.setDireccion(direccionPaciente);
        nuevoPaciente.setCiudad(ciudadPaciente);
        nuevoPaciente.setIsapre(isaprePaciente);
        nuevoPaciente.setDonante(esDonante);
        
        Registro pacienteController = new Registro();
        boolean pacienteAgregado;
        try {
            pacienteAgregado = pacienteController.agregarPaciente(nuevoPaciente);
            if(pacienteAgregado) {
                JOptionPane.showMessageDialog(rootPane, "Paciente Agregado Correctamente!","Éxito Agregando Paciente",1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo ingresar el paciente!","Falló Agregar Paciente",1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtn_agregarPacienteActionPerformed

    private void jRadio_pacienteFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacienteFemeninoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadio_pacienteFemeninoActionPerformed

    private void jRadio_pacienteConIsapreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacienteConIsapreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadio_pacienteConIsapreActionPerformed

    private void jRadio_pacienteConIsapreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteConIsapreMouseClicked
        // TODO add your handling code here:
        this.jRadio_pacienteConIsapre.setSelected(true);
        this.jRadio_pacienteSinIsapre.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteConIsapreMouseClicked

    private void jRadio_pacienteSinIsapreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteSinIsapreMouseClicked
        // TODO add your handling code here:
        this.jRadio_pacienteSinIsapre.setSelected(true);
        this.jRadio_pacienteConIsapre.setSelected(false);
        
        
    }//GEN-LAST:event_jRadio_pacienteSinIsapreMouseClicked

    private void jRadio_pacienteConIsapreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteConIsapreMouseReleased
        // TODO add your handling code here:
        this.jRadio_pacienteConIsapre.setSelected(true);
        this.jRadio_pacienteSinIsapre.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteConIsapreMouseReleased

    private void jRadio_pacienteSinIsapreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_pacienteSinIsapreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_pacienteSinIsapreActionPerformed

    private void jRadio_pacienteSinIsapreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteSinIsapreMouseReleased
        // TODO add your handling code here:
        this.jRadio_pacienteSinIsapre.setSelected(true);
        this.jRadio_pacienteConIsapre.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteSinIsapreMouseReleased

    private void jRadio_pacienteFemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteFemeninoMouseClicked
        // TODO add your handling code here:
        this.jRadio_pacienteFemenino.setSelected(true);
        this.jRadio_pacienteMasculino.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteFemeninoMouseClicked

    private void jRadio_pacienteFemeninoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteFemeninoMouseReleased
        // TODO add your handling code here:
        this.jRadio_pacienteFemenino.setSelected(true);
        this.jRadio_pacienteMasculino.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteFemeninoMouseReleased

    private void jRadio_pacienteMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteMasculinoMouseClicked
        // TODO add your handling code here:
        this.jRadio_pacienteMasculino.setSelected(true);
        this.jRadio_pacienteFemenino.setSelected(false);
        
    }//GEN-LAST:event_jRadio_pacienteMasculinoMouseClicked

    private void jRadio_pacienteMasculinoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadio_pacienteMasculinoMouseReleased
        // TODO add your handling code here:
        this.jRadio_pacienteMasculino.setSelected(true);
        this.jRadio_pacienteFemenino.setSelected(false);
    }//GEN-LAST:event_jRadio_pacienteMasculinoMouseReleased

    private void jBtn_salirAgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_salirAgregarPacienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_salirAgregarPacienteActionPerformed

    private void jBtn_limpiarDatosPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_limpiarDatosPacienteActionPerformed
        // TODO add your handling code here:
        this.jText_rutPaciente.setText("");
        this.jText_nombrePaciente.setText("");
        this.jRadio_pacienteFemenino.setSelected(false);
        this.jRadio_pacienteMasculino.setSelected(false);
        this.jRadio_pacienteConIsapre.setSelected(false);
        this.jRadio_pacienteSinIsapre.setSelected(false);
        this.jText_edadPaciente.setText("");
        this.jText_direccionPaciente.setText("");
        this.jText_ciudadPaciente.setText("");
        this.jCheckBox_esDonante.setSelected(false);
    }//GEN-LAST:event_jBtn_limpiarDatosPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_agregarPaciente;
    private javax.swing.JButton jBtn_limpiarDatosPaciente;
    private javax.swing.JButton jBtn_salirAgregarPaciente;
    private javax.swing.JCheckBox jCheckBox_esDonante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_nombreCarrera;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadio_pacienteConIsapre;
    private javax.swing.JRadioButton jRadio_pacienteFemenino;
    private javax.swing.JRadioButton jRadio_pacienteMasculino;
    private javax.swing.JRadioButton jRadio_pacienteSinIsapre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_ciudadPaciente;
    private javax.swing.JTextField jText_direccionPaciente;
    private javax.swing.JTextField jText_edadPaciente;
    private javax.swing.JTextField jText_nombrePaciente;
    private javax.swing.JTextField jText_rutPaciente;
    // End of variables declaration//GEN-END:variables
}
